apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 2Gi
  selector: 
    matchLabels: 
      dataFor: mysql-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 2Gi
  selector: 
    matchLabels: 
      dataFor: mysql-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 2Gi
  selector: 
    matchLabels: 
      dataFor: mysql-2