apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-0
  labels: 
    dataFor: mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: datadir-mysql-0
  capacity:
    storage: 2Gi
  hostPath:
    path: /Volumes/SSDHOME/dev/git/k8s-mariadb-cluster/data/datadir-mysql-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-1
  labels: 
    dataFor: mysql-1
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: datadir-mysql-1
  capacity:
    storage: 2Gi
  hostPath:
    path: /Volumes/SSDHOME/dev/git/k8s-mariadb-cluster/data/datadir-mysql-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-2
  labels: 
    dataFor: mysql-2
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: datadir-mysql-2
  capacity:
    storage: 2Gi
  hostPath:
    path: /Volumes/SSDHOME/dev/git/k8s-mariadb-cluster/data/datadir-mysql-2/